---
title: "Jean-Baptiste Guiffard"
output:
  html_document:
    toc: false
    number_sections: false
    theme: flatly
    highlight: textmate
    css: style_1.css
---

<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />


--- 

## About

I am an assistant professor in economics at [Université de Rouen-Normandie](https://www.univ-rouen.fr/), affiliated with the [LERN](https://lern.univ-rouen.fr/). 

I was formerly a postdoctoral researcher at [Télécom Paris](https://www.telecom-paris.fr/fr/ecole/departements-enseignement-recherche/sciences-economiques-sociales), affiliated with the Centre de Recherche en Économie et Statistique ([CREST](https://crest.science/)) and the [Institut Polytechnique de Paris](https://www.ip-paris.fr/). I am also an associate researcher at the [UMR Développement et Sociétés](https://umr-devsoc.pantheonsorbonne.fr/), and I teach at [École Polytechnique](https://www.polytechnique.edu/) and the Institut d'Études du Développement de la Sorbonne ([IEDES](https://iedes.pantheonsorbonne.fr/)).

I hold a PhD in economics from Université Paris 1 Panthéon-Sorbonne. My research lies at the intersection of digital and development economics, with a focus on causal impact evaluation and geospatial data analysis. Beyond connectivity, my recent work explores the role of digital platforms and artificial intelligence in shaping labor market dynamics.


<!---

I am also strongly committed to teaching and research dissemination. I designed and taught an advanced course on R programming and climate data analysis, and I regularly contribute to training sessions, workshops, and student supervision. My work is embedded in collaborative research projects, including the ANR JuGe project on marital dispute resolution in West Africa, and I am actively involved in networks such as ITS, AFEDEV, and the *Evidence Policy Impact Lab*.

--->

---

## News
<!---
- 📚 New publication: Guiffard, J.-B. (*forthcoming*). Measuring Broadband Diffusion and Impact Using Infrastructure Data. *Revue d'Economie du Développement*.
- organisation de la conférence au LERN
--->

- 📢 I joined the [LERN](https://lern.univ-rouen.fr/) team as a assistant professor in September 2025!
- 📢 *On the job market 2024-2025!*
- 📚 New Working paper: [*From Bytes to Business: Mobile Broadband, Firm Creations and Digital Divide in Tunisia*](https://erf.org.eg/publications/from-bytes-to-business-mobile-broadband-firm-creations-and-digital-divide-in-tunisia/) (2025).

<!---
- 🎓 PhD defended in Sept. 2024 at Université Paris 1.
- 🏆 Winner of the [TPRC 2024 Student Paper Award](https://www.tprcweb.com/student-paper-competition-finalists).  
--->


---

## Research 

### 📚 Publications

1. Guiffard J.-B. (2024). Valuing the Virtual: The Impact of Fiber to the Home on Property Prices in France.  *Telecommunications Policy*, 48(4), 102732. doi: [10.1016/j.telpol.2024.102732](https://doi.org/10.1016/j.telpol.2024.102732).

2. Kergall, P. & Guiffard, J.-B. (2024). Impact of Broadband Internet on Preventive Healthcare Behaviours in Senegal. *Economie et Statistique / Economics and Statistics*, 542, 99–123. doi: [10.24187/ecostat.2024.542.2113](https://doi.org/10.24187/ecostat.2024.542.2113).

3. Guiffard, J. B. (2025). Measuring broadband Internet diffusion and impact using infrastructure data. *Revue d'économie du développement*, 33(3), 235-242. doi: [10.3917/edd.393.0235](https://doi.org/10.3917/edd.393.0235).


### 📄 Working Papers

1. [**From Connection to Coordination: High-Speed Internet and Protests in Africa**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4247083) (2024)
  
2. [**Welfare Cost of Mobile Spectrum (Mis)allocation**](https://cepr.org/publications/dp18016) (2022) --- with Marc Ivaldi, Julienne Liang and Louise Aïmène

3. [**From Bytes to Business: Mobile Broadband, Firm Creations and Digital Divide in Tunisia**](https://erf.org.eg/publications/from-bytes-to-business-mobile-broadband-firm-creations-and-digital-divide-in-tunisia/) (2025) --- with Mohamed Ali Marouani

### 📑 Ongoing Research


1. **Measuring AI Substitutability and Complementarity in Developing Countries’ Labor Markets: Evidence from Online Job Postings Data.** (2025) --- with Minh-Phuong Le

2. **The impact of fixed and mobile broadband on firm performances in Tunisia** (2025) --- with Jawhar Abidi, Massimiliano Calì and Mohamed Ali Marouani.


---

## Experience & Education

<div class="timeline-section">
<div class="timeline-part experience-bg">
<h3 class="timeline-heading">💼 Experience</h3>


<div class="timeline-item">
<div class="timeline-date">2025 – </div>
<div class="timeline-content">
<h4>Assistant Professor – LERN (Université de Rouen Normandie)</h4>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">2024 – 2025</div>
<div class="timeline-content">
<h4>Postdoctoral Researcher – CREST (Télécom Paris)</h4>
<p>Research on broadband infrastructure and platforms (ANR HYBRID).</p>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">2022 – 2024</div>
<div class="timeline-content">
<h4>Teaching Assistant (ATER Full-time) – Paris I Panthéon-Sorbonne University (IEDES)</h4>
</div>
</div>


<div class="timeline-item">
<div class="timeline-date">2019 – 2022</div>
<div class="timeline-content">
<h4>Research Fellow – Orange, Regulatory Affairs</h4>
<p>Worked on spectrum policy, competition in telecom markets, and regulatory impact assessments.</p>
</div>
</div>

</div>

<div class="timeline-part education-bg">
<h3 class="timeline-heading">🎓 Education</h3>
<div class="timeline-item">
<div class="timeline-date">2024</div>
<div class="timeline-content">
<h4>PhD in Economics – Université Paris 1 Panthéon-Sorbonne</h4>
<p>Dissertation: <em>Essays in Digital Economics: Three Impact Evaluations of Broadband Internet</em></p>
</div>
</div>


<div class="timeline-item">
<div class="timeline-date">2018 – 2019</div>
<div class="timeline-content">
<h4>Master Degree in Economic expertise of development – Paris I - Panthéon-Sorbonne University</h4>
<p>Focus on development economics, microeconometrics, impact evaluation.</p>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">2018</div>
<div class="timeline-content">
<h4>Holder of secondary-school teaching diploma in Economic and Social Sciences</h4>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">2011 – 2013</div>
<div class="timeline-content">
<h4>Double Degree - Caen University</h4>
<p>Economics Degree and History Degree.</p>
</div>
</div>

</div>

</div>







