---
title: "Jean-Baptiste Guiffard - Teaching"
output:
  html_document:
    toc: false
    number_sections: false
    theme: flatly
    highlight: textmate
    css: style_1.css
---




---

## Teaching 2025-2026


*Work in progress*

<!---


- **Consommateurs et Producteurs** (Université de Rouen, L1)
<details><summary><strong>Course Materials</strong></summary>
<div class="course-block">
<ul> 
  <li>Courses:</li>
<ul>

</ul>
  <li>Seminars:</li>
<ul>

</ul>
  <li>Ressources:</li>
<ul>

</ul>
</ul>
</div>
</details>

- **Marchés et Systèmes de Prix** (Université de Rouen, L2)


- **Méthodes numériques appliquées** (Université de Rouen, L2)


- **Trade Policies** (Université de Rouen, L3)


- **Topics in Micro-Development Economics** (Université de Rouen, M1)


--->




## Archives

### 📊 Quantitative Methods & Econometrics


- <strong>Applied Econometrics</strong> (École Polytechnique, M1): A course focused on causal inference in social sciences. Topics include RCTs, IVs, RDD, diff-in-diff, event-study, matching, and synthetic control. I lead tutorials based on critical reading.
<details><summary><strong>Course Materials</strong></summary>
<div class="course-block">
<ul>
  <li><a href="https://synapses.polytechnique.fr/catalogue/2024-2025/ue/7646/ECO-52062-EP-econometrie-appliquee-2?from=D5">Synapses of the course</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics_polytechnique/Guiffard_TD_1_econometrie_appliquée.pdf">Slides of Introduction</a></li>
</ul>
</div>
</details>



- <strong>Applied Econometrics</strong> (IEDES, Paris 1 Panthéon-Sorbonne M1): Regression techniques with a focus on nonlinearities, interaction effects, heteroskedasticity, and count/discrete choice models. The course includes theoretical sessions and seminars using R.
<details><summary><strong>Course Materials</strong></summary>
<div class="course-block">
<ul> 
  <li>Courses:</li>
<ul>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/Cours_1_basics.pdf">Review of Basics I</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/Cours_2_basics.pdf">Review of Basics II</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/Cours_3_hetero.pdf">Heteroscedasticity</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/Cours_4_lpm_probit_logit.pdf">The LPM, probit, logit models</a></li>
</ul>
  <li>Seminars:</li>
<ul>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/TD1_enonce.pdf">TD 1</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/TD2_enonce.pdf">TD 2</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/TD3_enonce.pdf">TD 3</a></li>
</ul>
  <li>Ressources:</li>
<ul>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/Jeffrey_M._Wooldridge_Introductory_Econometrics_A_Modern_Approach__2012.pdf">Wooldridge, J. M. (2012). Introductory econometrics a modern approach.</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/Caffo_Regression models for data science in R_2015.pdf">Caffo, B. (2015). Regression models for data science in R. A companion book for the Coursera Regression Models class.</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/econometrics/effet_interaction.pdf">Jean-François Bickel. Les effets d'interaction.</a></li>
</ul>
</ul>
</div>
</details>




- <strong>Collection and analysis of quantitative and qualitative data</strong> (UFTAM, M2): Course on research design, survey techniques, and mixed data analysis. Includes a final empirical project using R.




### 🌍 Development Economics & Policy

- <strong>Development Measurement</strong> (IEDES, M1): Covers poverty, inequality, and well-being indicators; measurement issues and aggregation/comparison methods.

- <strong>Development Economics</strong> (IEDES, M1): TDs covering core theories, development aid, and public policy.

- <strong>Conferences on policy and project in development</strong> (IEDES, M2): A professionalization-oriented course involving guest talks from alumni and practitioners from institutions like the World Bank, AFD, OECD, and NGOs.


### 📋 Data Science & Replication

- <strong>Climate and Data</strong> (IEDES, M2): Teaching R and QGIS for climate and development data analysis. Includes data scraping, visualization, and geospatial mapping.
<details><summary><strong>Course Materials</strong></summary>
<div class="course-block">
<ul> 
  <li>Courses:</li>
<ul>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/data_climate/slides/Data_climate_cours_1.pdf">The Basics of R / Manipulating dataset with the DPLYR package</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/data_climate/slides/Data_climate_cours_2.pdf">Graphic representations with GGPLOT</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/data_climate/slides/Data_climate_cours_3.pdf">Making maps with R</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/data_climate/slides/Data_climate_cours_4.pdf">Web scraping with R</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/data_climate/slides/Data_climate_cours_5.pdf">Extracting and analyzing textual data using R</a></li>
</ul>
  <li>Training:</li>
<ul>
  <li><a href="https://github.com/jeanbaptisteguiffard/jeanbaptisteguiffard.github.io/tree/gh-pages/courses/data_climate/training">Github repository - Training</a></li>
  <li><a href="https://github.com/jeanbaptisteguiffard/intro_r_IEDES/archive/refs/heads/main.zip">Github repository - Introduction to R</a></li>
</ul>
  <li>Resources:</li>  
<ul>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/ressources/R/Cheatsheet_BASE_R.pdf">Cheatsheet Base R</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/ressources/R/Cheatsheet_DPLYR_TIDYR_R.pdf">Cheatsheet DPLYR and TIDYR R</a></li>
  <li><a href="https://jeanbaptisteguiffard.github.io/courses/ressources/R/Cheatsheet_GGPLOT2_R.pdf">Cheatsheet GGPLOT R</a></li>
  <li><a href="https://github.com/spatialdataworkshop/spatialdataworkshop.github.io">Github repository - Spatial Data Workshop 2023</a></li>
</ul>

</ul>
</div>
</details>


- <strong>Data Exploration and Modelling</strong> (IEDES, M1): STATA-based analysis of African firm survey data, focusing on gender wage inequality and labor discrimination.

- <strong>Tutored Projects in Development Economics</strong> (IEDES, M2): Replication of the paper “This Mine is Mine! How Minerals Fuel Conflicts in Africa” (Berman et al., 2017) using R and STATA. Covers geospatial data, modeling, reproducibility, and empirical presentation skills.
<details><summary><strong>Course Materials</strong></summary>
<div class="course-block">
<ul> 
  <li>Training:</li>
<ul>
  <li><a href="https://github.com/jeanbaptisteguiffard/jeanbaptisteguiffard.github.io/tree/gh-pages/courses/projet_tutore">Github repository - Training</a></li>
</ul>
</ul>
</div>
</details>





<!---
- The classical regression model

- Heteroscedasticity

- Non-linear models

**Data Exploration and Modelling (Inequalities, Discrimination)**

**Tutored Projects in Development Economics**

ARCHIVES ?

## IEDES - Master mention Etudes du Développement


### Master 1 - Econometrics

This course deepens the basics of econometrics, providing students with a solid understanding of the estimation and modelling techniques essential for analysing economic problems related to development. The following topics will be covered: 

1. The classical regression model

2. Properties of the OLS estimator in large samples

3. Heteroscedasticity: The problem and correction methods

4. Non-linear models: Probit and Logit

5. Count models: Poisson models

### [**Master 2 - Climate and Data**](https://jeanbaptisteguiffard.github.io/courses_climatedata.html)


To become familiar with climate issues and to understand the construction of sustainable development indicators, this course proposes: 

1. Intensive training in R software 

2. Advanced skills in data collection, processing, and analysis on R (graphical representations, maps, data extractions, web scraping, textual analysis. . . )

3. A common theme: climate data and sustainable development indicators.



**Statistics with R**

Lessons:

- The Basics of R

- Measurement and Descriptive Statistics

- Inference and Statistical Tests

- Simple and Multiple Regressions

--->



