---
title: "Jean-Baptiste Guiffard"
date: "`r Sys.Date()`"
geometry: "left=0.40in,top=0.3in,right=0.75in,bottom=0.1in"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Garamond}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0pt}
  - \fancyfoot[C]{\thepage}
  - \setlength{\parindent}{0pt}
  - \setlength{\parskip}{6pt}
  - \usepackage{multicol}
  - \usepackage{array}
---


\begin{minipage}[t]{0.55\textwidth}
\raggedright
\textbf{Contact information}\\
Email: \href{mailto:jean-baptiste.guiffard@univ-rouen.fr}{jean-baptiste.guiffard@univ-rouen.fr} \\
Phone: +33 6 87 96 61 05 \\
Address: 3 avenue Pasteur, 76000 Rouen, France \\
Website: \href{https://jeanbaptisteguiffard.github.io/}{jeanbaptisteguiffard.github.io}
\end{minipage}
\hfill
\begin{minipage}[t]{0.35\textwidth}
\raggedleft
\textbf{Personal information}\\
Nationality: French \\
Date of Birth: January 9, 1995 \\
\href{https://www.linkedin.com/in/jeanbaptisteguiffard}{LinkedIn} \\
\href{https://ideas.repec.org/f/pgu799.html}{RePEc}\\
\href{https://scholar.google.fr/citations?user=BnfXmC4AAAAJ&hl=fr&oi=ao}{GoogleScholar}
\end{minipage}


# Research Fields
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

**Primary:** Digital Economics

**Secondary:** Development Economics, Economic Geography, Industrial Organization



# Current Positions
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- Assistant Professor in Economics, Université de Rouen, [LERN](https://lern.univ-rouen.fr/) (2025-)

- Associate researcher at [UMR Développement & Sociétés](https://umr-devsoc.pantheonsorbonne.fr/)

- [Evidence Policy Impact Lab Member](https://www.smu.tn/fondation-smu/epi-lab-member-jean-baptiste-guiffard)


# Past Positions
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- Post-doctoral researcher, Telecom-Paris, CREST (2024 - 2025)

# Doctoral Studies
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}


- **Paris I - Panthéon-Sorbonne University** (November 2019 - September 2024)  
  *PhD degree in Economics*
  - Thesis title : *"Essays in Digital Economics: Three Impact Evaluations of Broadband Internet"*
  - Supervised by Mohamed Ali Marouani (CES, D&S, Paris-1 Panthéon-Sorbonne University) and François Roubaud (DIAL, IRD & Paris-Dauphine University).
  - Commitee: Jenny Aker, Marc Bourreau, Joël Cariolle, François Combarnous, Georges Houngbonon.
  
# Pre-Doctoral Studies
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- **Paris I - Panthéon-Sorbonne University** (2018 - 2019)\
  *Master Degree - Economic expertise of development, Summa cum laude, Valedictorian*
  
- **Paris VIII - Vincennes-Saint-Denis University** (2017 - 2018)\
  *Master 1 in Economics and Sociology, Valedictorian*
  - Holder of secondary-school teaching diploma in Economic and Social Sciences (2018)
  
- **Caen University** (2013 - 2017)\
  *Double Degree:*
  - *Economics Degree, Summa cum Laude, Valedictorian*
  - *History Degree, with honours*


# Publications
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

1. Guiffard J.-B. (2024). Valuing the Virtual: The Impact of Fiber to the Home on Property Prices in France.  *Telecommunications Policy*, 48(4), 102732. doi: [10.1016/j.telpol.2024.102732](https://doi.org/10.1016/j.telpol.2024.102732).

2. Kergall, P. & Guiffard, J.-B. (2024). Impact of Broadband Internet on Preventive Healthcare Behaviours in Senegal. *Economie et Statistique / Economics and Statistics*, 542, 99-123. doi: [10.24187/ecostat.2024.542.2113](https://doi.org/10.24187/ecostat.2024.542.2113).

3. Guiffard, J.-B. (*forthcoming*). Measuring Broadband Diffusion and Impact Using Infrastructure Data. *Revue d'Economie du Développement*.


# Working Papers
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

1. [**From Connection to Coordination: High-Speed Internet and Protests in Africa**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4247083) (2024)
  
2. [**Welfare Cost of Mobile Spectrum (Mis)allocation**](https://cepr.org/publications/dp18016) (2022) --- with Marc Ivaldi, Julienne Liang and Louise Aïmène

3. [**From Bytes to Business: Mobile Broadband, Firm Creations and Digital Divide in Tunisia**](https://erf.org.eg/publications/from-bytes-to-business-mobile-broadband-firm-creations-and-digital-divide-in-tunisia/) (2025) --- with Mohamed Ali Marouani

# Research Projects
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

<!---
1. **Digital platforms, high-speed Internet, and the transition from informal to formal employment in Brazil** (2025) --- with Joël Cariolle
--->

1. **Measuring AI Substitutability and Complementarity in Developing Countries’ Labor Markets: Evidence from Online Job Postings Data.** (2025) --- with Minh-Phuong Le

2. **The impact of fixed and mobile broadband on firm performances in Tunisia** (2025) --- with Jawhar Abidi, Massimiliano Calì and Mohamed Ali Marouani.

<!---
2. **Migration and intergenerational transmission of marriage-related practices in West Africa over the long run: Evidence from oral genealogies** (2023) --- with Antoine Castet, Karine Marazyan, and Munir Squires
--->

<!---
%{\bf Migration Dynamics in West Africa on Long Period} \hfill { 2022} 
%\\{ \textit {Work in Progress (with Karine Marazyan and Antoine Castet)}} 
{\bf What Do Randomistas Tell us about Governance ? A Systematic Review of Randomized Control Trials in the Field of Governance } \hfill { 2019} 
\\{ \textit {Master Thesis with François Roubaud and Mireille Razafindrakoto, IRD-Dial}} 
 The Relationship between License Duration and Telecom Investment in Africa and the Middle East : an Econometric Analysis} \hfill { 2020} 
\\{ \textit {Working paper}} 
--->


# Seminars and Conferences
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}


**2026**

[Development Economics Research - Connect webinar](https://dev-connect.org/webinar/research-seminar-6/) (Discussant), Online.



**2025**


Télécom-Paris AI Reading Group, Télécom-Paris, Palaiseau, France.
[International Conference on Development Economics (ICDE)](https://icde2025.sciencesconf.org/), EconomiX, Nanterre, France.
[11th annual AFREN Conference](https://afren.fr/3en_2025_cfp/), EconomiX, Nanterre, France.
[41èmes Journées de Microéconomie Appliquée (JMA)](https://jma2025.sciencesconf.org/), Université de Poitiers, France.
[73rd Congress of the French Economic Association (AFSE)](https://afse2025.sciencesconf.org/), ENS Paris-Saclay, Gif-sur-Yvette, France. 
[ERF 31st Annual Conference](https://erf.org.eg/conference/erf-31st-annual-conference), Cairo, Egypt.
[Paris Conference on Digital Economics 2025](https://www.digitaleconomics-paris.fr/conference-2025) (Discussant), Palaiseau, France.
[2025 ADRES Job Market Conférence](https://adres2025.sciencesconf.org), BETA, University of Strasbourg, France.


**2024**

AFREN Doctoral Worskhop, Palaiseau, France. [52nd Research Conference on Communications, Information, and Internet Policy](http://www.tprcweb.com/overview-2024), Washington, USA. [International Conference on Development Economics (ICDE)](https://icde2024.sciencesconf.org/), AMSE, Marseille, France. 

**2023**

[20th World Congress of the International Economic Association](https://ieawc2023.org/), Universidad EAFIT, Medellin, Colombia. [9th FESP-Paris 1 Research Workshop](https://fesp-eg.org/wp-content/uploads/2023/03/Call_9thFEPS_Paris1.pdf), Paris 1 Panthéon-Sorbonne, Paris, France. UMR Développement & Sociétés/CIRED PhD Poster Session, Paris, France. [51st Research Conference on Communications, Information, and Internet Policy](http://www.tprcweb.com/overview-2023), Washington, USA. [7th Nordic Development Research Conference](https://www.nordev2023.se/), Uppsala University, Uppsala, Sweden. [UMR Développement & Sociétés PhD Seminar](https://umr-devsoc.pantheonsorbonne.fr/), Paris 1 Panthéon-Sorbonne, Paris, France. [32nd ITS European Conference](https://itseurope.org/2023/), UNED, Madrid, Spain. [71st Congress of the French Economic Association (AFSE)](https://afse2023.sciencesconf.org/), SciencesPo, Paris, France. [1st Welfare & Policy Conference](https://wapsociety.org/event/conference-individual-and-collective-responses-to-a-troubled-world), BSE, Bordeaux, France. [18th Doctorissimes PhD Conference](https://sites.google.com/site/doctorissimes3/18th-doctorissimes-2023), CES, Paris, France.


**2022**

[Young Economist Seminar](https://www.digitaleconomics-paris.fr/young-economist-seminar), Telecom-Paris, Palaiseau, France. [25th QED (Quantative Economics Doctorate Network) Jamboree](https://www.vgse.at/about-vgse/qed-network/), University of Vienna, Vienna, Austria. [31st ITS European Regional Conference](https://itseurope.org/2022/), Chalmers University of Technology, Goteborg, Sweden. [EADI conference](https://iedes.pantheonsorbonne.fr/evenements/iedes-eadi-france-journee-detude-internationale), Agence Française de Développement, Paris, France.



# Professional experiences
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- **Paris I - Panthéon-Sorbonne University, Nogent-sur-Marne, France** (2022 - 2024)  
  *Teaching Assistant in Economics (ATER Full-time)*

- **Orange SA, Issy-les-Moulineaux, France** (2019 - 2022)\
  *Research Economist, Europe and Economics division, Department of Regulation* 

- **Audiovisual Council, Paris, France** 2019\
  *Data scientist, Department of Studies* - [The spread of fake news on social media - a study of the Twitter service](https://www.csa.fr/Informer/Collections-du-CSA/Focus-Toutes-les-etudes-et-les-comptes-rendus-synthetiques-proposant-un-zoom-sur-un-sujet-d-actualite/La-propagation-des-fausses-informations-sur-les-reseaux-sociaux-etude-de-la-plateforme-Twitter)
  
# Teaching
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- **Rouen Normandie University, Rouen, France** (2025 - *present*)\
  *Assistant professor*
  - *Microeconomics* (lecture and seminar) - L1
  - *Microeconomics* (lecture) - L2
  - *Applied numerical methods (Introduction to R)* - L2
  - *Trade Policies* (lecture) - L3
  - *Topics in Development economics* - M2

- **Ecole Polytechnique, Palaiseau, France** (2024 - 2026)\
  *Assistant Lecturer of Pauline Rossi and Clement Malgouyres in Applied Econometrics* - M1

- **Paris I - Panthéon-Sorbonne University, Nogent-sur-Marne, France** (2024 - 2025)\
  *Lecturer in Economics*
  - *Climate and Data* (an Introduction to R and an education on data and the construction of sustainable development indicators.) - M2
  - *Applied Econometrics* - M1
  - *Data Exploration and Modelling (Inequalities, Discrimination)* - M1

- **Paris I - Panthéon-Sorbonne University, Nogent-sur-Marne, France** (2023 - 2024)\
  *Teaching Assistant in Economics (ATER Full-time)*
  - *Development Measurement* (lecture) - M1
  - *Development Economics* (seminar) - M1
  - *Climate and Data* - M2
  - *Alumni Conferences* - M2
  - *Applied Econometrics* - M1
  - *Tutored Projects in Development Economics* - M1
  - *Data Exploration and Modelling (Inequalities, Discrimination)* - M1


- **Paris I - Panthéon-Sorbonne University, Nogent-sur-Marne, France** (2022 - 2023)\
  *Teaching Assistant in Economics (ATER Part-time)*
  - *Development Measurement* (Labor and Employment in Developing Countries) - M1
  - *Quantitative Methods training course* - M1
  - *Climate and Data* - M2
  - *Applied Econometrics* - M1
  - *Tutored Projects in Development Economics* - M1

- **Paris I - Panthéon-Sorbonne University / UFTAM, Tunisie** (2022)\
  *Lecturer in Collection and analysis of quantitative and qualitative data (master level)*

- **Paris I - Panthéon-Sorbonne University** (2021)\
  *Assistant Lecturer of Catherine Doz in Econometrics (undergraduate level)* 

- **Caen University** (2016-2017)\
  *Teaching Assistant in microeconomics, macroeconomics and inferential statistics (undergraduate level)*



# Service to the profession
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- **LERN, Rouen, France** (2026) \
  *Member of the local organizing committee of the International Conference on Development Economics (ICDE2026)*

- **LERN, Rouen, France** (2025 - *Present*)\
  *Co-organization of the LERN seminar*

- **Telecom-Paris, Palaiseau, France** (2025 - *Present*)\
  *Co-organization of the Télécom-Paris Working group and Reading group"*

- **Telecom-Paris, Palaiseau, France** (2025) \
  *Member of the organization team of the Paris Conference on Digital Economics*

- **IEDES / UMR Développement et Sociétés, Nogent-sur-Marne, France** (2021 - 2025)\
  *Co-organization of the seminar "Au Tour de Nos Matériaux"*
  - [AuToMat](https://jeanbaptisteguiffard.github.io/automat.html) - Multidisciplinary methodological seminar

- **UMR Développement et Sociétés, Nogent-sur-Marne, France** (2022 - 2025) \
  *Representative of young researchers at the laboratory council* 

- **Member of the Board of Directors of the French Association for Development Economics (AFEDEV)** (2023 - *Present*) \
  [*Communication team*](https://afedev.fr/)
  
- **UMR Développement et Sociétés and PSE, Nogent-sur-Marne, France** (December 2023)\
  *Co-organization of a [Workshop on spatial data in economics](https://umr-devsoc.pantheonsorbonne.fr/evenements/journee-detudes-donnees-spatiales-nouvelles-sources-nouvelles-perspectives)* 

<!---  
with [Antoine Castet](https://sites.google.com/view/antoinecastet) (UMR Développement & Sociétés), [Pascale Champalaune](https://pchampalaune.github.io/) (PSE) and [Julia Paul-Venturine](https://julia-paulventurine.github.io/) (PSE)
--->

- **UMR Développement et Sociétés, Nogent-sur-Marne, France** (October 2023)\
  *Co-organization of a joint UMR DEVSOC and CIRED PhD poster session*


- **Referee for journals**: *Journal of International Development*; *Revue internationale des études du développement*; *Telematics and Informatics*

- **Scientific Committee**: *ICDE* (2026, 2025); *West-African Digital Transformations Forum - Research Workshop* (2026); *International Workshop of the UNESCO Chair "Défis partagés du développement"* (2026)

# Grants and Awards
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- Best Student Paper (2024) - [52nd Research Conference on Communications, Information, and Internet Policy](https://www.tprcweb.com/student-paper-competition-finalists), Washington, USA (1,000$).

- Funding Bonus Qualité Recherche (BQR) for the organization of the AuToMat seminar (2,200€).

- Member of the ANR JuGe coordinated by Karine Marazyan, Charlotte Guénard and Paola Villar (300,000€).

- Funding for speaker travel to the AuToMat seminar (650€)

- Funding for the organization of a Workshop on spatial data (1,300€)


# Technical Skills
\vspace{-23pt}
\noindent\rule{\textwidth}{0.2pt}

- **Languages**: French, English
- **Programming Language**: R, Python, STATA, SAS, LaTeX, Web scraping
